import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import ModalContextProvider from "../HOC/ModalContext";
import { About, Possibilities, Welcome } from "../sections";

const Home: NextPage = () => {
    return (
        <ModalContextProvider>
            <Layout>
                <Head>
                    <title>New Era</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                </Head>

                <main className="font-body">
                    <Welcome />
                    <About />
                    <Possibilities />
                </main>
            </Layout>
        </ModalContextProvider>
    );
};

export default Home;
