import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";

const Home: NextPage = () => {
    return (
        <Layout>
            <Head>
                <title>New Era</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <main className="font-body">
                <h1 className="text-primary">
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
            </main>
        </Layout>
    );
};

export default Home;
